#!/bin/sh

PREREQ="ifdown"

prereqs() {
    echo "$PREREQ"
}

case "$1" in
    prereqs)
        prereqs
        exit 0
    ;;
esac

if grep -q ^VLAN= /conf/initramfs.conf; then
    . /conf/initramfs.conf
fi

for VLAN_IFACE in ${VLAN:-*}; do
    SOURCE_IFACE=$(echo $VLAN_IFACE | cut -d":" -f1)
    VLAN_ID=$(echo $VLAN_IFACE | cut -d":" -f2)
    ip link delete $SOURCE_IFACE.$VLAN_ID
done
