#!/bin/sh

PREREQ="cloud-initramfs-dyn-netconf"

prereqs() {
    echo "$PREREQ"
}

case "$1" in
    prereqs)
        prereqs
        exit 0
    ;;
esac

. /scripts/functions
. /conf/initramfs.conf
. /conf/conf.d/*.conf

if [ -z "$BOND" ]; then
    exit 0
fi

for BOND_IFACE in ${BOND:-*}; do
    BOND_DEVICE=$(echo $BOND_IFACE | cut -d":" -f1)
    log_begin_msg "Bringing down $BOND_DEVICE"
    ip link delete $BOND_DEVICE
    rm /run/net-$BOND_DEVICE.conf \
       /run/netplan/$BOND_DEVICE.yaml
    log_end_msg
done

exit 0
