#!/bin/sh

PREREQ="ifdown"

prereqs() {
    echo "$PREREQ"
}

case "$1" in
    prereqs)
        prereqs
        exit 0
    ;;
esac

. /scripts/functions
. /conf/initramfs.conf
. /conf/conf.d/*.conf

if [ -z "$VLAN" ]; then
    exit 0
fi

for VLAN_IFACE in ${VLAN:-*}; do
    SOURCE_IFACE=$(echo $VLAN_IFACE | cut -d":" -f1)
    VLAN_ID=$(echo $VLAN_IFACE | cut -d":" -f2)
    log_begin_msg "Bringing down $SOURCE_IFACE.$VLAN_ID"
    ip link delete $SOURCE_IFACE.$VLAN_ID
    log_end_msg
done
