#!/bin/sh

PREREQ=""

prereqs() {
    echo "$PREREQ"
}

case "$1" in
    prereqs)
        prereqs
        exit 0
    ;;
esac

if grep -q ^BOND= /conf/initramfs.conf; then
    . /conf/initramfs.conf
    modprobe bonding $BOND_MODE
fi

for BOND_IFACE in ${BOND:-*}; do
    BOND_DEVICE=$(echo $BOND_IFACE | cut -d":" -f1)
    BOND_SLAVES=$(echo $BOND_IFACE | cut -d":" -f2 | sed "s/,/ /g" )
    ip link add $BOND_DEVICE type bond
    for BOND_SLAVE in $BOND_SLAVES; do
        ip link set $BOND_SLAVE master bond0
    done
done

exit 0
