#!/bin/sh

PREREQ=""

prereqs() {
    echo "$PREREQ"
}

case "$1" in
    prereqs)
        prereqs
        exit 0
    ;;
esac

. /scripts/functions
. /conf/initramfs.conf

if [ -z "$VLAN" ]; then
    exit 0
fi

modprobe 8021q

for VLAN_IFACE in ${VLAN:-*}; do
    SOURCE_IFACE=$(echo $VLAN_IFACE | cut -d":" -f1)
    VLAN_ID=$(echo $VLAN_IFACE | cut -d":" -f2)
    log_begin_msg "Bringing up $SOURCE_IFACE.$VLAN_ID"
    ip link add link $SOURCE_IFACE name $SOURCE_IFACE.$VLAN_ID type vlan id $VLAN_ID
    ip link set $SOURCE_IFACE up
    ip link set $SOURCE_IFACE.$VLAN_ID up
    log_end_msg
done

exit 0
