#!/bin/sh
PREREQ=""
prereqs()
{
     echo "$PREREQ"
}

case $1 in
prereqs)
     prereqs
     exit 0
     ;;
esac

. /usr/share/initramfs-tools/hook-functions
# Begin real processing below this line

if grep -q ^BOND= /conf/initramfs.conf; then
    manual_add_modules bonding
    copy_exec /sbin/ifenslave /sbin
fi
